### PR TITLE
Ardent version downgrade

### PR DESCRIPTION
**Pull request by mikaelarguedas**
this performs a version downgrade to 0.4.0 for the ardent release

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
Except being ugly, can anything go wrong if the changelogs don't have monotonic version bump ?

**Comment by wjwwood** [comment]
Since they have to be different I don't see another way to do it more cleanly.

**Comment by mikaelarguedas** [comment]
sounds good thanks for confirming :+1:

**Comment by dirk-thomas** [comment]
The script updating the changlog files certainly assumes strict order on the version numbers: e.g. https://github.com/ros-infrastructure/catkin_pkg/blob/6b5020466784350a954ca33400a8854cf688ee44/src/catkin_pkg/changelog_generator.py#L173 So I would suggest to keep them in order - also the ardent branch doesn't necessarily need to contain the bouncy version entry.

**Comment by mikaelarguedas** [comment]
Looks like downgrades actually don't work: http://build.ros2.org/view/Asrc_uX/job/Asrc_uX__desktop__ubuntu_xenial__source/1/console

Apparently the debian changelog is ordered by icreasing changelog order https://github.com/ros2-gbp/variants-release/commit/fb83f1bde5e865ddb30a41cbae8d902c36e5db94#diff-45c17c0a080fbe29e2b8ded8940aa1e8

**Comment by mikaelarguedas** [comment]
> also the ardent branch doesn't necessarily need to contain the bouncy version entry.

You mean removing the 0.5.* commits from the ardent branch and force push it so that they're not picked up by the changelog generator ?

**Comment by dirk-thomas** [comment]
> You mean removing the 0.5.* commits from the ardent branch and force push it so that they're not picked up by the changelog generator ?

Yeah, that would be one option.

**Comment by mikaelarguedas** [comment]
Ok I'm planning on force pushing this branch to the ardent branch: https://github.com/ros2/variants/commits/ardent_to_forcepush
(Removed all the changelog update and version tagging commits).

Once pushed I'll delete the 0.4.0 tag and run `catkin_prepare release --version 0.4.0`

Does that sound reasonable ?

**Pull request merged**
