### PR TITLE
Desktop-full, perception and simulation variants

### PR DESCRIPTION
**Pull request by chapulina**
* Implementation for this REP PR: https://github.com/ros-infrastructure/rep/pull/334

### CODE REVIEW

**Comment by chapulina** [comment]
CI shouldn't be triggered for Foxy or Galactic for PRs targeting `master`. This should fix it:

* https://github.com/ros/rosdistro/pull/33010

**Comment by chapulina** [comment]
@ros-pull-request-builder retest this please

**Comment by chapulina** [comment]
@ros-pull-request-builder retest this please

**Comment by chapulina** [comment]
@ros-pull-request-builder retest this please

**Review by clalancette — APPROVED** [review]

**Review by tfoote — APPROVED** [review]

**Comment by tfoote** [comment]
@ros-pull-request-builder retest this please

**Comment by nuclearsandwich** [comment]
The Rpr job is failing because rqt_top is missing / regressed

```
00:00:29.797 The following packages have unmet dependencies:
00:00:29.797  ros-rolling-rqt-common-plugins : Depends: ros-rolling-rqt-top but it is not installable
```

**Review by nuclearsandwich — APPROVED** [review]

**Comment by clalancette** [comment]
FYI, https://github.com/ros-visualization/rqt_common_plugins/pull/465 should fix the PR jobs, once it is merged and released.

**Pull request merged**
