### PR TITLE
Add rosbag2 to ros variants

### PR DESCRIPTION
**Pull request by Karsten1987**
I wasn't sure whether it best belongs to `ros_core`, but ultimately settled on `ros_base`.

### CODE REVIEW

**Comment by ivanpauno** [comment]
from pre-waffle triagge: @Karsten1987 Can you assign yourself in this one?

**Comment by Karsten1987** [comment]
@nuclearsandwich just a friendly ping

**Review by jacobperron — APPROVED** [review]
Seems like a reasonable place to add it. It would be good to get others to weigh in.

**Comment by emersonknapp** [comment]
This looks good to me! I was just thinking "we should get rosbag in a variant" and here you're way ahead of me :)

**Review by emersonknapp — APPROVED** [review]

**Comment by nuclearsandwich** [comment]
Forgive me for asking rather than digging for myself, but does rosbag2 depend (either directly or indirectly) on the ros1_bridge and therefore ROS 1? If so that's quite heavyweight for ros_base.

**Comment by Karsten1987** [comment]
It does not. The [rosbag2_bag_v2 plugin](https://github.com/ros2/rosbag2_bag_v2) lives in its own repository.

**Review by nuclearsandwich — APPROVED** [review]

**Pull request merged**
